import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { headers } from "next/headers";

export async function POST(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: tripId } = await params;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const body = await req.json().catch(() => ({})) as { email?: string };
  const invitedEmail: string | null = body.email?.trim() || null;

  // Get trip's group_id and title
  const { data: trip } = await supabase
    .from("trips")
    .select("group_id, title")
    .eq("id", tripId)
    .single();
  if (!trip) return NextResponse.json({ error: "Trip not found" }, { status: 404 });

  // Create invite (token generated by DB default)
  const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();
  const { data: invite, error } = await supabase
    .from("group_invites")
    .insert({
      group_id: trip.group_id,
      invited_by: user.id,
      expires_at: expiresAt,
      invited_email: invitedEmail,
    })
    .select("token")
    .single();

  if (error || !invite) {
    return NextResponse.json({ error: "Failed to create invite" }, { status: 500 });
  }

  // ── Build the invite URL ──────────────────────────────────────────────────
  const headersList = await headers();
  const host   = headersList.get("host") ?? "localhost:3000";
  const scheme = host.startsWith("localhost") ? "http" : "https";
  const inviteUrl = `${scheme}://${host}/invite/${invite.token}`;

  // ── Send email if address provided and Resend is configured ──────────────
  if (invitedEmail && process.env.RESEND_API_KEY) {
    try {
      await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${process.env.RESEND_API_KEY}`,
        },
        body: JSON.stringify({
          from: process.env.EMAIL_FROM ?? "Holiday Planner <noreply@holidayplanner.app>",
          to: invitedEmail,
          subject: `You've been invited to plan a trip: ${trip.title}`,
          html: buildInviteEmail(inviteUrl, trip.title as string),
        }),
      });
    } catch {
      // Email failure is non-fatal — invite token still returned
    }
  }

  return NextResponse.json({ token: invite.token, inviteUrl });
}

function buildInviteEmail(inviteUrl: string, tripTitle: string) {
  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f8fafc; margin: 0; padding: 40px 20px;">
  <div style="max-width: 480px; margin: 0 auto; background: white; border-radius: 16px; overflow: hidden; border: 1px solid #e2e8f0;">
    <div style="background: linear-gradient(135deg, #1e1b4b 0%, #6366f1 100%); padding: 32px 32px 28px; text-align: center;">
      <div style="font-size: 32px; margin-bottom: 8px;">✈️</div>
      <h1 style="color: white; margin: 0; font-size: 22px; font-weight: 700;">Holiday Planner</h1>
    </div>
    <div style="padding: 32px;">
      <h2 style="color: #0f172a; margin: 0 0 12px; font-size: 18px;">You've been invited!</h2>
      <p style="color: #475569; margin: 0 0 24px; line-height: 1.6;">
        Someone has invited you to collaborate on a trip: <strong>${tripTitle}</strong>.
        Click the button below to accept the invite and join the planning group.
      </p>
      <a href="${inviteUrl}"
        style="display: inline-block; background: #6366f1; color: white; text-decoration: none;
               padding: 12px 28px; border-radius: 10px; font-weight: 600; font-size: 15px;">
        Accept invite →
      </a>
      <p style="color: #94a3b8; font-size: 12px; margin: 24px 0 0; line-height: 1.5;">
        This invite link expires in 7 days and can only be used once.
        If you don't have an account yet, you'll be asked to create one first.
      </p>
    </div>
  </div>
</body>
</html>
  `.trim();
}
