"use client";

function esc(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

interface Props {
  tripTitle: string;
  departureDate: string;
  returnDate: string;
  members: { user_id: string; name: string }[];
  totalExpenses: number;
  budgetPerPerson: number | null;
  destinationCountry: string | null;
}

export default function TripReportExport({
  tripTitle,
  departureDate,
  returnDate,
  members,
  totalExpenses,
  budgetPerPerson,
  destinationCountry,
}: Props) {
  function printReport() {
    const dep = esc(new Date(departureDate).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" }));
    const ret = esc(new Date(returnDate).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" }));
    const memberList = members.map(m => esc(m.name)).join(", ");
    const budget = budgetPerPerson ? `€${esc(String(budgetPerPerson))} per person` : "No budget set";
    const spent = `€${esc(totalExpenses.toFixed(2))} logged`;
    const safeTitle = esc(tripTitle);
    const safeCountry = destinationCountry ? esc(destinationCountry) : null;

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Trip Report — ${safeTitle}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 700px; margin: 40px auto; color: #1e293b; line-height: 1.6; }
    h1 { font-size: 2rem; font-weight: 800; margin-bottom: 4px; }
    .subtitle { color: #64748b; font-size: 1rem; margin-bottom: 32px; }
    .section { margin-bottom: 24px; }
    .section h2 { font-size: 0.75rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #94a3b8; margin-bottom: 8px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
    .stat { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 16px; }
    .stat .value { font-size: 1.5rem; font-weight: 800; color: #4f46e5; }
    .stat .label { font-size: 0.8rem; color: #64748b; margin-top: 2px; }
    .members { background: #f0f9ff; border: 1px solid #bae6fd; border-radius: 12px; padding: 16px; }
    footer { margin-top: 40px; font-size: 0.75rem; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 16px; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <h1>${safeTitle}</h1>
  <p class="subtitle">${dep} → ${ret}${safeCountry ? ` · ${safeCountry}` : ""}</p>

  <div class="section">
    <h2>Dates</h2>
    <div class="grid">
      <div class="stat"><div class="value">${dep}</div><div class="label">Departure</div></div>
      <div class="stat"><div class="value">${ret}</div><div class="label">Return</div></div>
    </div>
  </div>

  <div class="section">
    <h2>Budget</h2>
    <div class="grid">
      <div class="stat"><div class="value">${budget}</div><div class="label">Budget</div></div>
      <div class="stat"><div class="value">${spent}</div><div class="label">Expenses logged</div></div>
    </div>
  </div>

  <div class="section">
    <h2>Group (${members.length} member${members.length !== 1 ? "s" : ""})</h2>
    <div class="members">${memberList}</div>
  </div>

  <footer>Generated by Holiday Planner · ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</footer>
</body>
</html>`;

    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 300);
  }

  return (
    <button onClick={printReport} className="btn-ghost text-sm flex items-center gap-2">
      🖨️ Export trip report
    </button>
  );
}
